---
spring:
  profiles: caching-a-local

kubernetes:
  enabled: true
  accounts:
  - name: k8s-acc-0
    requiredGroupMembership: []
    providerVersion: V2
    permissions:
      READ:
      - read1
      - read2
      WRITE:
      - write1
      - write2
    dockerRegistries: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces:
    - oes
    omitNamespaces: []
    kinds: []
    omitKinds:
    - clusterRoleBinding
    - controllerRevision
    - customResourceDefinition
    - role
    - roleBinding
    - persistentVolume
    - apiService
    - validatingWebhookConfiguration
    - podPreset
    - mutatingWebhookConfiguration
    - podSecurityPolicy
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/ubuntu/.hal/k8spin/staging/dependencies/1031763043-config
    oAuthScopes: []
    onlySpinnakerManaged: true

---
spring:
  profiles: caching-1-local

kubernetes:
  enabled: true
  accounts:
  - name: k8s-acc-100
    requiredGroupMembership: []
    providerVersion: V2
    permissions:
      READ:
      - read1
      - read2
      WRITE:
      - write1
      - write2
    dockerRegistries: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces:
    - oes
    omitNamespaces: []
    kinds: []
    omitKinds:
    - clusterRoleBinding
    - controllerRevision
    - customResourceDefinition
    - role
    - roleBinding
    - persistentVolume
    - apiService
    - validatingWebhookConfiguration
    - podPreset
    - mutatingWebhookConfiguration
    - podSecurityPolicy
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/ubuntu/.hal/k8spin/staging/dependencies/1031763043-config
    oAuthScopes: []
    onlySpinnakerManaged: true

---
spring:
  profiles: caching-2-local

kubernetes:
  enabled: true
  accounts:
  - name: k8s-acc-200
    requiredGroupMembership: []
    providerVersion: V2
    permissions:
      READ:
      - read1
      - read2
      WRITE:
      - write1
      - write2
    dockerRegistries: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces:
    - oes
    omitNamespaces: []
    kinds: []
    omitKinds:
    - clusterRoleBinding
    - controllerRevision
    - customResourceDefinition
    - role
    - roleBinding
    - persistentVolume
    - apiService
    - validatingWebhookConfiguration
    - podPreset
    - mutatingWebhookConfiguration
    - podSecurityPolicy
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/ubuntu/.hal/k8spin/staging/dependencies/1031763043-config
    oAuthScopes: []
    onlySpinnakerManaged: true

